apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cs-qube
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{.Values.ingress.host}}
      http:
        paths:
          - path: {{.Values.ingress.path}}
            pathType: {{.Values.ingress.pathType}}
            backend:
              service:
                name: cs-qube
                port:
                  number: {{.Values.service.port}}
