apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Values.persistentVolume.name}}
  labels:
    app: cs-qube
spec:
  storageClassName: {{.Values.persistentVolume.storageClassName}}
  capacity:
    storage: {{.Values.persistentVolume.capacity}}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{.Values.persistentVolume.hostPath}}
