apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.persistentVolumeClaim.name}}
spec:
  storageClassName: {{.Values.persistentVolume.storageClassName}}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: {{.Values.persistentVolume.name}}
