apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  access_key_id: {{.Values.app.credentials.access_key_id}}
  secret_access_key: {{.Values.app.credentials.secret_access_key}}
