apiVersion: v1
kind: Service
metadata:
  name: cs-qube
  labels:
    app: cs-qube
spec:
  ports:
    - port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetPort}}
  selector:
    app: cs-qube
